# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_0eWdQ9-Q5F87qYPWalIYjaWXzkKQSfV
"""

import streamlit as st
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# -----------------------------
# Streamlit Page Config
# -----------------------------
st.set_page_config(
    page_title="AI Mess Manager",
    layout="centered"
)

st.title("🍽️ ML + AI-Powered Mess Manager")
st.caption("Smart food quantity prediction & wastage reduction system")

# -----------------------------
# Global Config
# -----------------------------
random.seed(42)

students_strength = 450
meals = ["Breakfast", "Lunch", "Dinner"]

menu_items_list = [
    "Dal Tadka", "Rajma Masala", "Kadhi Pakora", "Paneer Butter Masala",
    "Aloo Sabzi", "Mixed Veg", "Chole", "Bhindi Fry", "Fried Rice",
    "Poori", "Chapatti", "Paratha", "Jeera Rice", "Raita", "Salad"
]

# -----------------------------
# Generate Historical Dataset
# -----------------------------
@st.cache_data
def generate_data():
    data = []
    start_date = datetime.today() - timedelta(days=30)

    for i in range(30):
        date = start_date + timedelta(days=i)
        day_of_week = date.weekday()

        for meal in meals:
            base = students_strength
            if meal == "Breakfast":
                base -= 90
            if day_of_week == 0:  # Monday effect
                base -= 30

            attendance = base + random.randint(-20, 20)
            menu_items = random.sample(menu_items_list, random.randint(3, 5))

            rice = attendance * 0.12
            chapatti = attendance * 3
            dal = attendance * 0.06
            sabzi = attendance * 0.10

            if any(d in ["Dal Tadka", "Rajma Masala", "Kadhi Pakora"] for d in menu_items):
                rice *= 1.2
                chapatti *= 0.85

            if any(d in ["Paneer Butter Masala", "Aloo Sabzi", "Mixed Veg", "Chole", "Bhindi Fry"] for d in menu_items):
                chapatti *= 1.2
                rice *= 0.85

            data.append([
                date.date(), meal, attendance, menu_items,
                round(rice, 2), int(chapatti), round(dal, 2), round(sabzi, 2)
            ])

    df = pd.DataFrame(
        data,
        columns=["Date", "Meal", "Attendance", "Menu",
                 "Rice_kg", "Chapatti_count", "Dal_kg", "Sabzi_kg"]
    )

    for item in menu_items_list:
        df[item] = df["Menu"].apply(lambda x: 1 if item in x else 0)

    return df


df = generate_data()

# -----------------------------
# Train ML Models
# -----------------------------
@st.cache_resource
def train_models(df):
    X = df[["Attendance"] + menu_items_list]

    y_rice = df["Rice_kg"]
    y_chapatti = df["Chapatti_count"]
    y_dal = df["Dal_kg"]
    y_sabzi = df["Sabzi_kg"]

    X_train, _, y_rice_train, _ = train_test_split(X, y_rice, test_size=0.2, random_state=42)
    _, _, y_chap_train, _ = train_test_split(X, y_chapatti, test_size=0.2, random_state=42)
    _, _, y_dal_train, _ = train_test_split(X, y_dal, test_size=0.2, random_state=42)
    _, _, y_sabzi_train, _ = train_test_split(X, y_sabzi, test_size=0.2, random_state=42)

    rf_rice = RandomForestRegressor(n_estimators=100, random_state=42)
    rf_chap = RandomForestRegressor(n_estimators=100, random_state=42)
    rf_dal = RandomForestRegressor(n_estimators=100, random_state=42)
    rf_sabzi = RandomForestRegressor(n_estimators=100, random_state=42)

    rf_rice.fit(X_train, y_rice_train)
    rf_chap.fit(X_train, y_chap_train)
    rf_dal.fit(X_train, y_dal_train)
    rf_sabzi.fit(X_train, y_sabzi_train)

    return rf_rice, rf_chap, rf_dal, rf_sabzi


rf_rice, rf_chapatti, rf_dal, rf_sabzi = train_models(df)

# -----------------------------
# Prediction Functions
# -----------------------------
def ml_mess_prediction(students, menu):
    features = [students] + [1 if item in menu else 0 for item in menu_items_list]
    features_df = pd.DataFrame([features], columns=["Attendance"] + menu_items_list)

    rice = rf_rice.predict(features_df)[0]
    chapatti = rf_chapatti.predict(features_df)[0]
    dal = rf_dal.predict(features_df)[0]
    sabzi = rf_sabzi.predict(features_df)[0]

    return round(rice, 2), int(chapatti), round(dal, 2), round(sabzi, 2)


def ai_insights(students, menu, rice, chapatti):
    insights = []

    rice_ratio = rice / (students * 0.12)
    chap_ratio = chapatti / (students * 3)

    if rice_ratio > chap_ratio:
        insights.append("🍚 Rice-heavy menu detected.")
    elif chap_ratio > rice_ratio:
        insights.append("🫓 Chapatti-heavy menu detected.")
    else:
        insights.append("⚖️ Balanced rice & chapatti demand.")

    if "Paneer Butter Masala" in menu:
        insights.append("💡 Paneer dishes usually increase chapatti demand.")

    if students > 450:
        insights.append("⚠️ High attendance expected. Keep buffer stock ready.")

    confidence = min(95, 80 + random.randint(5, 15))
    return insights, confidence

# -----------------------------
# UI Inputs
# -----------------------------
st.subheader("📌 Input Details")

students = st.number_input(
    "Expected Number of Students",
    min_value=100,
    max_value=800,
    value=420
)

menu = st.multiselect(
    "Select Today's Menu",
    menu_items_list,
    default=["Dal Tadka", "Paneer Butter Masala", "Jeera Rice", "Chapatti", "Salad"]
)

# -----------------------------
# Prediction Button
# -----------------------------
if st.button("🔮 Predict Food Quantities"):
    rice, chapatti, dal, sabzi = ml_mess_prediction(students, menu)
    insights, confidence = ai_insights(students, menu, rice, chapatti)

    st.subheader("📦 Predicted Quantities")
    col1, col2 = st.columns(2)

    col1.metric("🍚 Rice (kg)", rice)
    col1.metric("🥣 Dal (kg)", dal)

    col2.metric("🫓 Chapatti (count)", chapatti)
    col2.metric("🥗 Sabzi (kg)", sabzi)

    st.subheader("🧠 AI Insights")
    for i in insights:
        st.write("•", i)

    st.success(f"✅ Prediction Confidence: {confidence}%")

# -----------------------------
# Footer
# -----------------------------
st.markdown("---")
st.caption("Developed for smart mess management using ML & AI")